### ISSUE TITLE
[BUG] Failed segmentation resnet-50 training

### ISSUE THREAD

**Issue by Only-bottle** [Nota-NetsPresso/netspresso-trainer#511]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues.

### Describe the bug

I'm trying to train the segmentation task with the resnet50 model, but I got an error.

### Reproduction

I only modified the data, training, environment, and logging configs and left the model config as is.

```
python train.py\
  --data config/data/local/voc12.yaml\
  --augmentation config/augmentation/segmentation.yaml\
  --model config/model/resnet/resnet50-segmentation.yaml\
  --training config/training.yaml\
  --logging config/logging.yaml\
  --environment config/environment.yaml
```

### Screenshot

![image](https://github.com/user-attachments/assets/3db529e2-22e2-48c3-be63-1cd5bc42137d)

### System Info

```shell
Branch: v1.0.1.b1
```

### Will you help us by submitting a PR?

- [ ] I will submit a PR about this issue.

**Comment by hglee98** [comment]
@Only-bottle 
I think the issue is caused by the missing data from the return_stage_idx in the backbone.params namespace. Could you try again with setting up the value like below?

![image](https://github.com/user-attachments/assets/6bfa0674-9d4a-42c4-9d1d-5613e792281c)

![image](https://github.com/user-attachments/assets/b6e8b889-66e5-45cd-96dd-d191d33f8824)

**Comment by Only-bottle** [comment]
I modified the return_stage_IDX and tried again, and it worked. thank you, @hglee98

**Comment by illian01** [comment]
I am currently working on the code so that when return_stage_idx is `None`, it defaults to `[last_stage_idx]`.
For example, in the case of ResNet, this would correspond to `[3]`. 
I'll be submitting a PR shortly.
